name: build

on: [workflow_dispatch]

jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    env:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4G'"
    steps:
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install ninja-build

    - name: Checkout
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Setup Java 21
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21
        cache: gradle

    - name: Make Sure INCREMENTAL GAME Is Latest
      working-directory: app/src/embed/assets
      run: |
        set -e
        git checkout master
        git pull origin master --ff-only
        rm -rf .github _notes assets/ikea build tooling

    - name: Build
      run: bash ./gradlew assembleEmbedNoRecord${{ matrix.build_type }} bundleEmbedRecord${{ matrix.build_type }}

    - name: Artifact APK
      uses: actions/upload-artifact@v6
      with:
        name: apks-${{ matrix.build_type }}
        path: app/build/outputs/apk
        if-no-files-found: error

    - name: Artifact AAB
      uses: actions/upload-artifact@v6
      with:
        name: aabs-${{ matrix.build_type }}
        path: app/build/outputs/bundle
        if-no-files-found: error

    - name: Artifact Debug Synbols
      uses: actions/upload-artifact@v6
      with:
        name: apks-${{ matrix.build_type }}
        path: app/build/outputs/native-debug-symbols
